# Generated by Django 6.1.2 on 2026-10-08 19:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Microarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome da instância do gerador', max_length=200, unique=True)),
                ('setores', models.JSONField(default=list, help_text='códigos dos setores censitários')),
                ('bairros', models.JSONField(default=list)),
                ('poligono', models.JSONField(blank=True, help_text='GeoJSON (lon, lat) da união dos setores', null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('moradores_censo', models.IntegerField(blank=True, null=True)),
                ('domicilios_censo', models.IntegerField(blank=True, null=True)),
                ('instancia_dir', models.CharField(help_text='pasta da instância (relativa a INSTANCES_DIR)', max_length=500)),
                ('ubs_node', models.BigIntegerField(help_text='nó da malha a pé onde fica a UBS')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microareas', to='core.equipe')),
            ],
            options={
                'verbose_name': 'microárea',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(help_text='linha em instance.gpkg (id do domicílio na instância)')),
                ('node', models.BigIntegerField(help_text='nó da malha a pé em frente à edificação')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('edificacao', models.IntegerField(blank=True, null=True)),
                ('n_moradores', models.PositiveIntegerField(default=1)),
                ('condicao', models.CharField(max_length=50)),
                ('peso', models.FloatField(help_text='peso clínico w')),
                ('intervalo_max_dias', models.PositiveIntegerField(help_text='intervalo máximo entre visitas P (dias)')),
                ('duracao_min', models.FloatField(help_text='duração da visita s (min)')),
                ('ultima_visita', models.DateField()),
                ('tw_inicio', models.FloatField(default=0, help_text='início da janela (min desde o início da jornada)')),
                ('tw_fim', models.FloatField(default=420, help_text='fim da janela (min desde o início da jornada)')),
                ('urgente', models.BooleanField(default=False)),
                ('grave', models.BooleanField(default=False)),
                ('microarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='core.microarea')),
            ],
            options={
                'verbose_name': 'domicílio',
                'ordering': ['microarea', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('jornada_min', models.FloatField(default=360, help_text='jornada nominal T (min)')),
                ('jornada_max_min', models.FloatField(default=420, help_text='jornada máxima Tmax (min)')),
                ('velocidade_m_min', models.FloatField(default=75, help_text='velocidade de caminhada (m/min)')),
                ('teto_graves', models.PositiveIntegerField(default=3, help_text='teto K de casos graves por dia')),
                ('microarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='core.microarea')),
            ],
            options={
                'verbose_name': 'agente (ACS)',
                'verbose_name_plural': 'agentes (ACS)',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('metodo', models.CharField(choices=[('guloso', 'guloso'), ('alns', 'ALNS'), ('milp', 'MILP')], max_length=10)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('viavel', 'viável'), ('com_violacoes', 'com violações')], max_length=20)),
                ('violacoes', models.JSONField(blank=True, default=list)),
                ('hora_inicio', models.TimeField(help_text='início da jornada usado no plano')),
                ('objetivo', models.FloatField()),
                ('caminhada_min', models.FloatField()),
                ('penalidade_residual', models.FloatField()),
                ('excesso_min', models.FloatField()),
                ('retorno_min', models.FloatField(help_text='H: retorno à UBS (min desde o início da jornada)')),
                ('n_candidatas', models.PositiveIntegerField(default=0)),
                ('n_fora_candidatas', models.PositiveIntegerField(default=0, help_text='viáveis que ficaram fora das candidatas')),
                ('runtime_s', models.FloatField(default=0)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('seeds_stats', models.JSONField(blank=True, null=True)),
                ('gap', models.FloatField(blank=True, null=True)),
                ('rota_geojson', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.agente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NaoAtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('inviavel', 'inviável'), ('urgencia_excedente', 'urgência excedente'), ('nao_coube', 'não coube'), ('teto_graves', 'teto de graves'), ('retirada_por_urgencia', 'retirada por urgência')], max_length=30)),
                ('penalidade', models.FloatField()),
                ('dias_sem_visita', models.PositiveIntegerField()),
                ('atraso_dias', models.PositiveIntegerField(help_text='dias além do intervalo máximo: max(0, d − P)')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nao_atendimentos', to='core.domicilio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_atendidas', to='core.plano')),
            ],
            options={
                'verbose_name': 'visita não atendida',
                'verbose_name_plural': 'visitas não atendidas',
            },
        ),
        migrations.CreateModel(
            name='ItemRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('chegada_min', models.FloatField()),
                ('inicio_min', models.FloatField()),
                ('fim_min', models.FloatField()),
                ('caminhada_min', models.FloatField(help_text='caminhada desde a parada anterior')),
                ('motivo', models.CharField(choices=[('urgencia', 'urgência'), ('atraso', 'atraso'), ('risco', 'risco'), ('rotina', 'rotina')], max_length=10)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_roteiro', to='core.domicilio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.plano')),
            ],
            options={
                'verbose_name': 'item do roteiro',
                'verbose_name_plural': 'itens do roteiro',
                'ordering': ['plano', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'verbose_name': 'UBS',
                'verbose_name_plural': 'UBS',
                'constraints': [models.UniqueConstraint(fields=('lat', 'lon'), name='ubs_coordenada_unica')],
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='ubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.ubs'),
        ),
        migrations.AddConstraint(
            model_name='domicilio',
            constraint=models.UniqueConstraint(fields=('microarea', 'codigo'), name='domicilio_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='plano',
            index=models.Index(fields=['agente', 'data'], name='core_plano_agente__8ddf4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='naoatendida',
            constraint=models.UniqueConstraint(fields=('plano', 'domicilio'), name='nao_atendida_unica'),
        ),
        migrations.AddConstraint(
            model_name='itemroteiro',
            constraint=models.UniqueConstraint(fields=('plano', 'ordem'), name='item_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='equipe',
            constraint=models.UniqueConstraint(fields=('ubs', 'nome'), name='equipe_nome_unico_por_ubs'),
        ),
    ]
